#include "cyrinx_golden.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Generated by scratch/hw20k/golden_vectors.py. Provides cyrinx_golden_cases[],
 * cyrinx_golden_ncases, and CYRINX_GOLDEN_FLOAT_ABS_TOL. */
#include "golden_manifest.h"

int cyrinx_golden_read(const char *dir, const char *relpath,
                       unsigned char **out, size_t *len) {
    if (!dir || !relpath || !out || !len) {
        return -1;
    }
    char path[4096];
    int n = snprintf(path, sizeof(path), "%s/%s", dir, relpath);
    if (n < 0 || (size_t)n >= sizeof(path)) {
        return -1;
    }
    FILE *f = fopen(path, "rb");
    if (!f) {
        return -1;
    }
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        return -1;
    }
    long sz = ftell(f);
    if (sz < 0 || fseek(f, 0, SEEK_SET) != 0) {
        fclose(f);
        return -1;
    }
    unsigned char *buf = (unsigned char *)malloc((size_t)sz ? (size_t)sz : 1);
    if (!buf) {
        fclose(f);
        return -1;
    }
    size_t got = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    if (got != (size_t)sz) {
        free(buf);
        return -1;
    }
    *out = buf;
    *len = (size_t)sz;
    return 0;
}

void cyrinx_golden_free(unsigned char *p) { free(p); }

int cyrinx_golden_verify_sizes(const char *dir, size_t *checked) {
    size_t seen = 0;
    int mismatches = 0;
    for (size_t ci = 0; ci < cyrinx_golden_ncases; ++ci) {
        const cyrinx_golden_case *c = &cyrinx_golden_cases[ci];
        for (size_t ai = 0; ai < c->n_artifacts; ++ai) {
            const cyrinx_golden_artifact *a = &c->artifacts[ai];
            unsigned char *buf = NULL;
            size_t len = 0;
            seen++;
            if (cyrinx_golden_read(dir, a->file, &buf, &len) != 0) {
                mismatches++;
                continue;
            }
            if (len != a->bytes) {
                mismatches++;
            }
            cyrinx_golden_free(buf);
        }
    }
    if (checked) {
        *checked = seen;
    }
    return mismatches;
}

size_t cyrinx_golden_case_count(void) { return cyrinx_golden_ncases; }

const char *cyrinx_golden_case_name(size_t i) {
    return i < cyrinx_golden_ncases ? cyrinx_golden_cases[i].name : NULL;
}

double cyrinx_golden_float_abs_tol(void) { return CYRINX_GOLDEN_FLOAT_ABS_TOL; }
