/* Generated by scratch/hw20k/golden_vectors.py — DO NOT EDIT. */
/* C-consumable manifest of the bulk-PHY golden vectors. */
#ifndef CYRINX_GOLDEN_MANIFEST_H
#define CYRINX_GOLDEN_MANIFEST_H
#include <stddef.h>

typedef struct {
    const char *stage, *file, *dtype, *tolerance, *sha256;
    size_t bytes;
} cyrinx_golden_artifact;

typedef struct {
    const char *name;
    size_t n_artifacts;
    const cyrinx_golden_artifact *artifacts;
} cyrinx_golden_case;

#define CYRINX_GOLDEN_FLOAT_ABS_TOL 1e-05

static const cyrinx_golden_artifact cyrinx_golden__qpsk_r12[] = {
    {"payload", "qpsk_r12/payload.bin", "uint8", "exact", "fe5c1de9b88c44e6f2e0097b5fd9fd2ba1d4f881d091aa00743bb670cbbe1615", 256},
    {"stream_with_crc", "qpsk_r12/stream_with_crc.bin", "uint8", "exact", "e75ff4c3e2234c17f9457656be9116e5fbeff76abbb0497cda0df72546c45216", 260},
    {"info_bits", "qpsk_r12/info_bits.bin", "uint8", "exact", "6e54a262885a8fd2afe5f5844e57b35bf38193019e0a320b7fac6733fa9479fa", 3266},
    {"pad_info_bits", "qpsk_r12/pad_info_bits.bin", "uint8", "exact", "d38d5644902e451163a94ceaf19c3899c594242b2f1830934b72d8d486c98cea", 1186},
    {"coded_bits", "qpsk_r12/coded_bits.bin", "uint8", "exact", "5ebf56c329b9dcef33a8f141880891f3fa516221432e72d21745616504edef18", 6544},
    {"punctured_bits", "qpsk_r12/punctured_bits.bin", "uint8", "exact", "5ebf56c329b9dcef33a8f141880891f3fa516221432e72d21745616504edef18", 6544},
    {"pad_fill_bits", "qpsk_r12/pad_fill_bits.bin", "uint8", "exact", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", 0},
    {"coded_filled_bits", "qpsk_r12/coded_filled_bits.bin", "uint8", "exact", "5ebf56c329b9dcef33a8f141880891f3fa516221432e72d21745616504edef18", 6544},
    {"interleave_perm", "qpsk_r12/interleave_perm.bin", "int64", "exact", "40ae7f73f500922b2541a8a8ccd0a2f4d3408109688bac2aca2687dee4034126", 52352},
    {"interleaved_bits", "qpsk_r12/interleaved_bits.bin", "uint8", "exact", "f0f9021190360421a279291e4f89270c0891ea7a977040edbcb44624fe71da5d", 6544},
    {"pilots", "qpsk_r12/pilots.bin", "complex64", "float", "a6e79e7a150d21ad3d23259adecb91e56a0bd18ed0a59d4b28b00b56bc5b58c3", 936},
    {"sync_freq", "qpsk_r12/sync_freq.bin", "complex64", "float", "f66e0abb3135272af5f2aaf48d29ab544a3758b958697f8f92139beb1de6c23b", 14960},
    {"data_freq", "qpsk_r12/data_freq.bin", "complex64", "float", "edbf5b13dc5274397e66e5e1779df9418b19b8c24dbca300ae73bb9ae3bb3b03", 29920},
    {"wave", "qpsk_r12/wave.bin", "float32", "float", "06f96d2e78164975101e7712d4afffb929dd0f126e91fd718779b4827ded7983", 92160},
    {"rx_wave", "qpsk_r12/rx_wave.bin", "float32", "input", "84ddd4d2a1f5dfa4b9a590553d8ef2be0cc6769337ecc5f53e609b18bee71a95", 113200},
    {"decoded_payload", "qpsk_r12/decoded_payload.bin", "uint8", "exact", "fe5c1de9b88c44e6f2e0097b5fd9fd2ba1d4f881d091aa00743bb670cbbe1615", 256},
};

static const cyrinx_golden_artifact cyrinx_golden__qam16_r34[] = {
    {"payload", "qam16_r34/payload.bin", "uint8", "exact", "7480da176862677585a8221d93ebfee8e79d6be888d66edc3b77ac69560f8eae", 1024},
    {"stream_with_crc", "qam16_r34/stream_with_crc.bin", "uint8", "exact", "b2a56994e7bc30e7cd458ff4c48c2849162a2412c41688e211728be08e436436", 1040},
    {"info_bits", "qam16_r34/info_bits.bin", "uint8", "exact", "e2ab608655436eec28c8566f08d172c27ba5c24187edb68f76d9a039c7868fe8", 9810},
    {"pad_info_bits", "qam16_r34/pad_info_bits.bin", "uint8", "exact", "b8db578caf6c1172fce805f032a2f087e00a0e8045a64b32609b38e5e6550498", 1490},
    {"coded_bits", "qam16_r34/coded_bits.bin", "uint8", "exact", "95c6c0974a308e03de7cbab41b14d4afa3f5668778b07a3947311875a4416859", 19632},
    {"punctured_bits", "qam16_r34/punctured_bits.bin", "uint8", "exact", "3e92fbb88cd7d09986d49ebe9427d03711fafd5209b5359870e22a80981ebea7", 13088},
    {"pad_fill_bits", "qam16_r34/pad_fill_bits.bin", "uint8", "exact", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", 0},
    {"coded_filled_bits", "qam16_r34/coded_filled_bits.bin", "uint8", "exact", "3e92fbb88cd7d09986d49ebe9427d03711fafd5209b5359870e22a80981ebea7", 13088},
    {"interleave_perm", "qam16_r34/interleave_perm.bin", "int64", "exact", "a34a6723d3d1eb8944dddb78768ca42a3e1b897a138ce7ab39881416bb16f216", 104704},
    {"interleaved_bits", "qam16_r34/interleaved_bits.bin", "uint8", "exact", "ab27063d5fcd54f87a6afdd8737ddb3dfb0446d34f9dca7da02bb87a00f66e85", 13088},
    {"pilots", "qam16_r34/pilots.bin", "complex64", "float", "a6e79e7a150d21ad3d23259adecb91e56a0bd18ed0a59d4b28b00b56bc5b58c3", 936},
    {"sync_freq", "qam16_r34/sync_freq.bin", "complex64", "float", "f66e0abb3135272af5f2aaf48d29ab544a3758b958697f8f92139beb1de6c23b", 14960},
    {"data_freq", "qam16_r34/data_freq.bin", "complex64", "float", "76b42ec476a6b664412c92d415e0023021c1e08429773683913f168ce6b74152", 29920},
    {"wave", "qam16_r34/wave.bin", "float32", "float", "9e249e863fe9c6b1571f4cf12e1a8b4b5e7b96edf82b75897987df3b4c5d9ca0", 92160},
    {"rx_wave", "qam16_r34/rx_wave.bin", "float32", "input", "e60f0678967c12607e22135aba7ad467cbeb438ce67df005eddb53ccd4795bde", 113200},
    {"decoded_payload", "qam16_r34/decoded_payload.bin", "uint8", "exact", "7480da176862677585a8221d93ebfee8e79d6be888d66edc3b77ac69560f8eae", 1024},
};

static const cyrinx_golden_artifact cyrinx_golden__qpsk_r23[] = {
    {"payload", "qpsk_r23/payload.bin", "uint8", "exact", "49de5eebd1a31dd8489582bf612c440f66c046e1eb94133df23a2f863a16660e", 512},
    {"stream_with_crc", "qpsk_r23/stream_with_crc.bin", "uint8", "exact", "01f741232c37d0a5dec4edd6c1e23cc90985b9fc4dfeb499dd53d7b54d214a79", 520},
    {"info_bits", "qpsk_r23/info_bits.bin", "uint8", "exact", "0a6b5ebfda7baedffb4fb0ba50345847cdd02f0621801507b270094ab11b9b8b", 4356},
    {"pad_info_bits", "qpsk_r23/pad_info_bits.bin", "uint8", "exact", "e2e4917f35f49f2799dc5aefbf9b18155e224db84e795148c0726c4ac8065ec0", 196},
    {"coded_bits", "qpsk_r23/coded_bits.bin", "uint8", "exact", "1279b32c15c402db3d0ec3e56961a2ef4080aa30043404fafd2904948dbadf9e", 8724},
    {"punctured_bits", "qpsk_r23/punctured_bits.bin", "uint8", "exact", "14ebd6eca17553111e765f85d273e1153a6e36d1620c5a691d0f1e5fe4c5418b", 6543},
    {"pad_fill_bits", "qpsk_r23/pad_fill_bits.bin", "uint8", "exact", "4bf5122f344554c53bde2ebb8cd2b7e3d1600ad631c385a5d7cce23c7785459a", 1},
    {"coded_filled_bits", "qpsk_r23/coded_filled_bits.bin", "uint8", "exact", "1cea9c9d1d65bff39f6add7ae49784fd242a299c2b0df787e427a4db7e4d4706", 6544},
    {"interleave_perm", "qpsk_r23/interleave_perm.bin", "int64", "exact", "40ae7f73f500922b2541a8a8ccd0a2f4d3408109688bac2aca2687dee4034126", 52352},
    {"interleaved_bits", "qpsk_r23/interleaved_bits.bin", "uint8", "exact", "1917bc083751e156f76b89daa4bb2d4c554ff634f2aee693908c3d27f673abbf", 6544},
    {"pilots", "qpsk_r23/pilots.bin", "complex64", "float", "a6e79e7a150d21ad3d23259adecb91e56a0bd18ed0a59d4b28b00b56bc5b58c3", 936},
    {"sync_freq", "qpsk_r23/sync_freq.bin", "complex64", "float", "f66e0abb3135272af5f2aaf48d29ab544a3758b958697f8f92139beb1de6c23b", 14960},
    {"data_freq", "qpsk_r23/data_freq.bin", "complex64", "float", "cc842000a8e91f5dfbcd79159aaa887a32d8d564843ce3349b63e68b2cab5b25", 29920},
    {"wave", "qpsk_r23/wave.bin", "float32", "float", "a1fa86cf14f68ad3aa71d577a0c15f040e6a8d52ac34629b27767dc9ba5581cd", 92160},
    {"rx_wave", "qpsk_r23/rx_wave.bin", "float32", "input", "ecac16f634573f9926b5e2d229de54d902a3eafe6da0b6546b559a42dc0a8106", 113200},
    {"decoded_payload", "qpsk_r23/decoded_payload.bin", "uint8", "exact", "49de5eebd1a31dd8489582bf612c440f66c046e1eb94133df23a2f863a16660e", 512},
};

static const cyrinx_golden_case cyrinx_golden_cases[] = {
    {"qpsk_r12", 16, cyrinx_golden__qpsk_r12},
    {"qam16_r34", 16, cyrinx_golden__qam16_r34},
    {"qpsk_r23", 16, cyrinx_golden__qpsk_r23},
};
static const size_t cyrinx_golden_ncases = 3;

#endif /* CYRINX_GOLDEN_MANIFEST_H */
