import Foundation

/// Deterministic, in-process, paired `ChatTransportClient`. Apps/Chat/
/// CONTRACT.md §2.
///
/// Two instances (constructed together via `makePair`) share one
/// `VirtualClock` and reference each other directly: A's `send(body:)`
/// builds a real envelope v1 byte buffer via `ChatEnvelopeCodec.encode`
/// (the same codec validated against the golden vectors) and B decodes
/// those exact bytes via `ChatEnvelopeCodec.decode` -- CONTRACT.md §2 point
/// 2's "envelope bytes actually cross the codec boundary," the literal
/// mechanism behind the C3-28 merge gate. There is no real network, audio,
/// or IPC involved (CONTRACT.md §2 point 1).
///
/// **Concurrency note:** this type is a deliberately single-threaded
/// discrete-event simulation (see `VirtualClock`'s documentation) driven by
/// one sequential caller -- a scenario runner or a test -- never by
/// concurrent tasks calling into the same pair simultaneously. It
/// deliberately does NOT conform to `Sendable` (not even `@unchecked`): it
/// holds genuinely unsynchronized mutable state (`connectionState`,
/// `outgoingMessages`, `pendingSendTokens`, ...), and an `@unchecked
/// Sendable` conformance would be a false promise that lets a future
/// caller (e.g. a `@MainActor` UI model plus a background task) share one
/// instance across concurrency domains without the compiler catching the
/// resulting data race -- the opposite of what "single sequential caller"
/// requires. Verified empirically (C3-28 review): removing the prior
/// `@unchecked Sendable` conformance compiles clean under this package's
/// default Swift 6 language mode (`swift-tools-version: 6.0`, no
/// `swiftLanguageMode` override) with zero new warnings or errors, and
/// every `swift test` case still passes -- nothing in this package or its
/// tests actually crosses an actor-isolation boundary with an instance of
/// this class, so the conformance was unused, not load-bearing.
public final class SimulatedChatTransportClient: ChatTransportClient {
    /// ASCII "MSGIDA__" -- see the message-ID generator seeding note below.
    private static let messageIdSeedTagA: UInt64 = 0x4D53_4749_4441_5F5F
    /// ASCII "MSGIDB__" -- see the message-ID generator seeding note below.
    private static let messageIdSeedTagB: UInt64 = 0x4D53_4749_4442_5F5F

    public let role: ChatClientRole
    public let scenario: ChatScenario
    public let localPeerId: Data

    let clock: VirtualClock
    /// Set (weakly, to avoid a retain cycle) by `makePair` right after
    /// construction. `weak` because the pair's two clients reference each
    /// other; whichever owns them externally (a test, `ChatScenarioRunner`)
    /// is the sole strong-reference holder.
    weak var peer: SimulatedChatTransportClient?

    /// Same-module-only hook `ChatScenarioRunner` uses to build one
    /// combined, chronologically ordered trace across both clients in a
    /// pair, without consuming (and thereby racing) each client's
    /// independent `events` `AsyncStream`. Not part of the public
    /// `ChatTransportClient` contract.
    var traceSink: ((ChatClientRole, Int64, ChatEvent) -> Void)?

    private let emitter = ChatEventEmitter()
    /// DECISION (not pinned by CONTRACT.md -- see §3's "Message IDs...
    /// generated by the sending client's own message-ID generation at
    /// send() time ... out of scope for this document to pin further"):
    /// each client gets its own message-ID generator, independent of the
    /// simulator-construction PRNG stream that CONTRACT.md §2 pins to
    /// *exactly* two draws (both consumed for peer IDs, with the document
    /// explicit that "No further scenario-independent draws" happen on
    /// that stream across all six scenarios). Reusing that stream for
    /// message IDs would contradict that "no further draws" statement, so
    /// message IDs are drawn from a second, independent `SplitMix64`
    /// seeded from `pairSeed XOR <fixed per-role tag>` -- deterministic per
    /// (scenario, seed) and reproducible run to run, but not a value this
    /// document pins across Swift and Kotlin (that cross-language
    /// agreement isn't required by this Swift-only implementation stage;
    /// see the C3-28 spec-stage report's unpinned-decisions list).
    private var messageIdPRNG: SplitMix64

    private(set) var started = false
    private var discoveryScheduled = false
    private var finished = false
    public private(set) var connectionState: ChatConnectionState = .disconnected(reason: nil)
    private(set) var discoveredPeer: ChatPeer?

    private var outgoingMessages: [String: ChatMessage] = [:]
    private var seenIncomingMessageIds: Set<String> = []
    private var pendingSendTokens: [String: [Int]] = [:]

    init(role: ChatClientRole, scenario: ChatScenario, seed: UInt64, clock: VirtualClock, localPeerId: Data) {
        self.role = role
        self.scenario = scenario
        self.clock = clock
        self.localPeerId = localPeerId
        let tag = role == .a ? Self.messageIdSeedTagA : Self.messageIdSeedTagB
        self.messageIdPRNG = SplitMix64(seed: seed ^ tag)
    }

    /// Constructs a paired, in-process simulated transport for `scenario`
    /// and `seed`, per CONTRACT.md §2's PRNG draw-order contract: draw 1's
    /// first 4 (big-endian) bytes become A's local peer ID (as later
    /// discovered by B); draw 2's, B's (as later discovered by A). Both
    /// draws happen here, at construction time, before virtual time starts
    /// advancing -- CONTRACT.md §2's "at simulator construction time"
    /// requirement.
    public static func makePair(
        scenario: ChatScenario,
        seed: UInt64,
        clock: VirtualClock = VirtualClock()
    ) -> (a: SimulatedChatTransportClient, b: SimulatedChatTransportClient) {
        var prng = SplitMix64(seed: seed)
        let draw1 = prng.next()
        let draw2 = prng.next()
        let peerIdA = Data(splitMix64BigEndianBytes(draw1).prefix(4))
        let peerIdB = Data(splitMix64BigEndianBytes(draw2).prefix(4))

        let clientA = SimulatedChatTransportClient(
            role: .a, scenario: scenario, seed: seed, clock: clock, localPeerId: peerIdA
        )
        let clientB = SimulatedChatTransportClient(
            role: .b, scenario: scenario, seed: seed, clock: clock, localPeerId: peerIdB
        )
        clientA.peer = clientB
        clientB.peer = clientA
        return (clientA, clientB)
    }

    public var events: AsyncStream<ChatEvent> { emitter.stream }

    // MARK: - ChatTransportClient

    public func start() async throws {
        guard !started else { return }
        started = true
        scheduleDiscoveryIfBothStarted()
    }

    public func stop() async {
        guard !finished else { return }
        finished = true
        emitter.finish()
    }

    public func connect(toPeer idHex: String) async throws {
        guard let discoveredPeer, discoveredPeer.id.hexString == idHex.lowercased() else {
            throw ChatSimulatedTransportError.unknownPeer
        }
        connectionState = .connecting
        emit(.connectionChanged(.connecting))

        // CONTRACT.md's DECISION (§3.1): the passive side (B) transitions
        // disconnected -> connected directly, with no `connecting` state of
        // its own -- so only the caller (A) emits `.connecting` above; both
        // sides get `becomeConnected()` scheduled below.
        let connectedAtMs = clock.nowMs + ChatSimTiming.connectHandshakeDelayMs
        clock.schedule(atMs: connectedAtMs) { [weak self] in self?.becomeConnected() }
        if let peer {
            clock.schedule(atMs: connectedAtMs) { [weak peer] in peer?.becomeConnected() }
        }
        scheduleScenarioPostConnect(connectedAtMs: connectedAtMs)
    }

    public func disconnect() async {
        // DECISION (not pinned by CONTRACT.md -- see its §1.2 note that the
        // `reason` vocabulary is free text, illustrated by a small fixed
        // set including "userInitiated"): none of the six scenarios call
        // `disconnect()` directly (peerLoss's disconnection is autonomous,
        // not driver-initiated), so this reason is this package's own
        // choice for the one case CONTRACT.md doesn't script.
        connectionState = .disconnected(reason: "userInitiated")
        emit(.connectionChanged(.disconnected(reason: "userInitiated")))
    }

    public func send(body: String) async throws -> String {
        guard connectionState == .connected else {
            throw ChatSimulatedTransportError.notConnected
        }
        let bodyBytes = [UInt8](body.utf8)
        guard bodyBytes.count <= ChatEnvelope.maxBodyLength else {
            throw ChatEnvelopeError.oversizeBody
        }

        let messageId = generateMessageId()
        let messageIdHex = messageId.hexString
        let envelope = ChatEnvelope(messageId: messageId, replyToId: nil, senderId: localPeerId, body: body)
        // CONTRACT.md §2 point 2: real envelope bytes, through the real
        // codec -- not a shortcut that skips it.
        let encoded = try ChatEnvelopeCodec.encode(envelope)

        let sentAtMs = clock.nowMs
        let message = ChatMessage(
            id: messageId,
            direction: .outgoing,
            body: body,
            senderPeerIdHex: localPeerId.hexString,
            sentAtWallClockMs: sentAtMs,
            status: .queued
        )
        outgoingMessages[messageIdHex] = message
        emit(.messageStatusChanged(messageIdHex: messageIdHex, status: .queued))

        scheduleSendOutcome(
            scenario.sendOutcome, messageIdHex: messageIdHex, encoded: encoded, sentAtMs: sentAtMs
        )
        return messageIdHex
    }

    /// CONTRACT.md §2's "Behavior outside the six scenario tables
    /// (pinned)": cancels the message's remaining scheduled status
    /// transitions and emits `messageStatusChanged(failed, failureReason:
    /// "cancelled")`, unless `messageIdHex` is unknown or already terminal
    /// (`.delivered` or `.failed`), in which case this is a no-op.
    public func cancelSend(messageIdHex: String) async {
        guard let message = outgoingMessages[messageIdHex] else { return }
        switch message.status {
        case .delivered, .failed:
            // Already terminal -- CONTRACT.md's no-op case. Note
            // `pendingSendTokens` may still hold this messageIdHex's
            // now-already-fired tokens (never proactively cleaned up once
            // fired -- `VirtualClock.cancel(_:)` on a fired token is
            // already a documented no-op), so the terminal-status check
            // here, not merely "is the key still in `pendingSendTokens`,"
            // is what makes this branch reachable at all.
            return
        case .queued, .transmitting:
            break
        }
        if let tokens = pendingSendTokens.removeValue(forKey: messageIdHex) {
            for token in tokens {
                clock.cancel(token)
            }
        }
        emitFailed(messageIdHex: messageIdHex, reason: "cancelled")
    }

    // MARK: - Discovery

    private func scheduleDiscoveryIfBothStarted() {
        guard let peer, peer.started, !discoveryScheduled, !peer.discoveryScheduled else { return }
        discoveryScheduled = true
        peer.discoveryScheduled = true
        let dueAtMs = clock.nowMs + ChatSimTiming.peerDiscoveryDelayMs
        // A's peerFound is always scheduled (and so always fires) before
        // B's, regardless of which client's start() happened to trigger
        // this, matching every one of CONTRACT.md §3's tables (A eventSeq0
        // then B eventSeq0, both at the same virtual time).
        let (first, second): (SimulatedChatTransportClient, SimulatedChatTransportClient) =
            role == .a ? (self, peer) : (peer, self)
        clock.schedule(atMs: dueAtMs) { [weak first] in first?.emitPeerFound() }
        clock.schedule(atMs: dueAtMs) { [weak second] in second?.emitPeerFound() }
    }

    private func emitPeerFound() {
        guard let peer else { return }
        let chatPeer = ChatPeer(id: peer.localPeerId, discoveredAtMs: clock.nowMs)
        discoveredPeer = chatPeer
        emit(.peerFound(chatPeer))
    }

    // MARK: - Connect handshake and scenario-scripted post-connect behavior

    private func becomeConnected() {
        connectionState = .connected
        emit(.connectionChanged(.connected))
    }

    private func scheduleScenarioPostConnect(connectedAtMs: Int64) {
        for step in scenario.postConnectSteps {
            let dueAtMs = connectedAtMs + step.deltaMs
            switch step.target {
            case .a:
                let target = role == .a ? self : peer
                clock.schedule(atMs: dueAtMs) { [weak target] in target?.applyPostConnect(step.template) }
            case .b:
                let target = role == .b ? self : peer
                clock.schedule(atMs: dueAtMs) { [weak target] in target?.applyPostConnect(step.template) }
            case .both:
                guard let peer else { continue }
                let (first, second): (SimulatedChatTransportClient, SimulatedChatTransportClient) =
                    role == .a ? (self, peer) : (peer, self)
                clock.schedule(atMs: dueAtMs) { [weak first] in first?.applyPostConnect(step.template) }
                clock.schedule(atMs: dueAtMs) { [weak second] in second?.applyPostConnect(step.template) }
            }
        }
    }

    private func applyPostConnect(_ template: ChatPostConnectStep.EventTemplate) {
        switch template {
        case .linkBudget(let budget):
            emit(.linkBudgetChanged(budget))
        case .connectionDegraded:
            connectionState = .degraded
            emit(.connectionChanged(.degraded))
        case .connectionRecoveredConnected:
            connectionState = .connected
            emit(.connectionChanged(.connected))
        case .connectionDisconnected(let reason):
            connectionState = .disconnected(reason: reason)
            emit(.connectionChanged(.disconnected(reason: reason)))
        case .peerLost(let reason):
            guard let peer else { return }
            emit(.peerLost(peerIdHex: peer.localPeerId.hexString, reason: reason))
        }
    }

    // MARK: - Send lifecycle

    private func scheduleSendOutcome(
        _ outcome: ChatSendOutcome, messageIdHex: String, encoded: Data, sentAtMs: Int64
    ) {
        let transmittingAtMs = sentAtMs + ChatSimTiming.sendTransmittingDelayMs
        var tokens: [Int] = []
        tokens.append(
            clock.schedule(atMs: transmittingAtMs) { [weak self] in
                self?.emitTransmitting(messageIdHex: messageIdHex)
            }
        )
        switch outcome {
        case .deliverNormally(let receiveDeltaMs, let deliveredDeltaMs):
            tokens.append(
                clock.schedule(atMs: transmittingAtMs + receiveDeltaMs) { [weak self] in
                    self?.peer?.receiveEnvelope(encoded)
                }
            )
            tokens.append(
                clock.schedule(atMs: transmittingAtMs + deliveredDeltaMs) { [weak self] in
                    self?.emitDelivered(messageIdHex: messageIdHex)
                }
            )
        case .fail(let deltaMs, let reason):
            tokens.append(
                clock.schedule(atMs: transmittingAtMs + deltaMs) { [weak self] in
                    self?.emitFailed(messageIdHex: messageIdHex, reason: reason)
                }
            )
        case .deliverWithDuplicate(let receiveDeltaMs, let redeliverDeltaMs, let deliveredDeltaMs):
            tokens.append(
                clock.schedule(atMs: transmittingAtMs + receiveDeltaMs) { [weak self] in
                    self?.peer?.receiveEnvelope(encoded)
                }
            )
            // Fault-injected retransmit: the SAME bytes, decoded again.
            // `receiveEnvelope`'s messageId dedup (CONTRACT.md's
            // `duplicateIncoming` scenario) is what suppresses this one.
            tokens.append(
                clock.schedule(atMs: transmittingAtMs + redeliverDeltaMs) { [weak self] in
                    self?.peer?.receiveEnvelope(encoded)
                }
            )
            tokens.append(
                clock.schedule(atMs: transmittingAtMs + deliveredDeltaMs) { [weak self] in
                    self?.emitDelivered(messageIdHex: messageIdHex)
                }
            )
        }
        pendingSendTokens[messageIdHex, default: []].append(contentsOf: tokens)
    }

    private func emitTransmitting(messageIdHex: String) {
        outgoingMessages[messageIdHex]?.status = .transmitting
        emit(.messageStatusChanged(messageIdHex: messageIdHex, status: .transmitting))
    }

    private func emitDelivered(messageIdHex: String) {
        outgoingMessages[messageIdHex]?.status = .delivered
        emit(.messageStatusChanged(messageIdHex: messageIdHex, status: .delivered))
    }

    private func emitFailed(messageIdHex: String, reason: String) {
        outgoingMessages[messageIdHex]?.status = .failed(reason: reason)
        emit(.messageStatusChanged(messageIdHex: messageIdHex, status: .failed(reason: reason)))
    }

    /// Called on the RECEIVING client with real encoded bytes produced by
    /// the peer's `send()` (CONTRACT.md §2 point 2). Decodes via the same
    /// strict codec validated against the golden vectors, applies
    /// messageId dedup (CONTRACT.md's `duplicateIncoming` scenario: exactly
    /// one `messageReceived` survives per distinct messageId, not zero, not
    /// two), and emits `messageReceived` for a new message. Malformed
    /// inbound bytes are silently dropped -- not exercised by any of the
    /// six scenarios, which only ever deliver bytes this same codec just
    /// encoded, but a real transport can't assume well-formed bytes from
    /// the wire either.
    func receiveEnvelope(_ encoded: Data) {
        guard let envelope = try? ChatEnvelopeCodec.decode(encoded) else { return }
        let messageIdHex = envelope.messageId.hexString
        guard !seenIncomingMessageIds.contains(messageIdHex) else { return }
        seenIncomingMessageIds.insert(messageIdHex)
        let message = ChatMessage(
            id: envelope.messageId,
            direction: .incoming,
            body: envelope.body,
            senderPeerIdHex: envelope.senderId.hexString,
            sentAtWallClockMs: clock.nowMs,
            status: .delivered
        )
        emit(.messageReceived(message))
    }

    // MARK: - Helpers

    @discardableResult
    private func emit(_ kind: ChatEvent.Kind) -> ChatEvent {
        let event = emitter.emit(kind)
        traceSink?(role, clock.nowMs, event)
        return event
    }

    private func generateMessageId() -> Data {
        let hi = messageIdPRNG.next()
        let lo = messageIdPRNG.next()
        var bytes = splitMix64BigEndianBytes(hi)
        bytes.append(contentsOf: splitMix64BigEndianBytes(lo))
        return Data(bytes)
    }
}
